### ISSUE TITLE
Tests failing in master

### ISSUE THREAD

**Issue by Robfrey** [DIPSAS/Dapper.Oracle#23]
I downloaded the latest copy of the solution. 14 of the 42 tests are failing, Including the DateTime test which I believe is causing my other open issue.

**Comment by epaulsen** [comment]
The tests are green for .Net core, but are failing for .net 452, and the error message says
`The provider is not compatible with the version of Oracle client`

This is caused by some Oracle-weirdness with how they locate their native dlls.  Need to find a way to run tests without an Oracle client installed, or we need to running tests for .net 4.5.2.

**Comment by epaulsen** [comment]
#21 fixed this.
